var exec = require('child_process').execSync
var path = require('path')

var symbols = exec(`nm -gU "${path.join(require.resolve('sodium-native'), '../prebuilds/darwin-x64/libsodium.dylib')}" | cut -f3 -d' ' | sed 's/^_//' | sed -r 's/_[a-z]*(bytes|primitive|strprefix|alg).*/\\U&\\E/'`).toString().trim().split('\n')
var native = new Set(Object.keys(require('sodium-native')).sort())
var js = new Set(Object.keys(require('sodium-javascript')).sort())

var missing = []

console.log(`
<!-- Generated by build-scripts/symbols.js with
     sodium-native@${require('sodium-native/package.json').version}
     sodium-javascript@${require('sodium-javascript/package.json').version} -->\
`)

console.log('| C Library Symbol | `sodium-native` | `sodium-javascript` |')
console.log('|:-----------------|:---------------:|:-------------------:|')
for (var i = 0; i < symbols.length; i++) {
  var s = symbols[i]
  if (!(native.has(s) || js.has(s))) missing.push(s)
  else console.log(`| \`${s}\` | ${native.has(s) ? ':white_check_mark:' : ':small_red_triangle:'} | ${js.has(s) ? ':white_check_mark:' : ':small_red_triangle:'} |`)
}

console.log('\n### Missing altogether (Ctrl + F friendly)\n')
console.log(missing.map(s => '`' + s + '`').join(', '))
